package com.servicio.modelo;

// Generated 09/12/2014 03:58:33 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", catalog = "aplicaciones")
public class Carrera implements java.io.Serializable {

	private Integer idCarrera;
	private Tarifa tarifa;
	private Usuario usuario;
	private String origen;
	private String destino;
	private String tiempo;
	private double velocidad;
	private double precio;
	private Date fecha;
	private String estado;

	public Carrera() {
	}

	public Carrera(Tarifa tarifa, Usuario usuario, String origen,
			String destino, String tiempo, double velocidad, double precio,
			Date fecha, String estado) {
		this.tarifa = tarifa;
		this.usuario = usuario;
		this.origen = origen;
		this.destino = destino;
		this.tiempo = tiempo;
		this.velocidad = velocidad;
		this.precio = precio;
		this.fecha = fecha;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_carrera", unique = true, nullable = false)
	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarifa", nullable = false)
	public Tarifa getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(Tarifa tarifa) {
		this.tarifa = tarifa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "origen", nullable = false, length = 50)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "destino", nullable = false, length = 50)
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	@Column(name = "tiempo", nullable = false, length = 45)
	public String getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "velocidad", nullable = false, precision = 22, scale = 0)
	public double getVelocidad() {
		return this.velocidad;
	}

	public void setVelocidad(double velocidad) {
		this.velocidad = velocidad;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 0)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
