package com.servicios.modelo;

// Generated 03/12/2014 01:14:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taxi generated by hbm2java
 */
@Entity
@Table(name = "taxi", catalog = "aplicaciones")
public class Taxi implements java.io.Serializable {

	private Integer idTaxi;
	private String placa;
	private String cooperativa;
	private String estado;
	private Set<Carrera> carreras = new HashSet<Carrera>(0);

	public Taxi() {
	}

	public Taxi(String placa, String cooperativa, String estado) {
		this.placa = placa;
		this.cooperativa = cooperativa;
		this.estado = estado;
	}

	public Taxi(String placa, String cooperativa, String estado,
			Set<Carrera> carreras) {
		this.placa = placa;
		this.cooperativa = cooperativa;
		this.estado = estado;
		this.carreras = carreras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_taxi", unique = true, nullable = false)
	public Integer getIdTaxi() {
		return this.idTaxi;
	}

	public void setIdTaxi(Integer idTaxi) {
		this.idTaxi = idTaxi;
	}

	@Column(name = "placa", nullable = false, length = 50)
	public String getPlaca() {
		return this.placa;
	}

	public void setPlaca(String placa) {
		this.placa = placa;
	}

	@Column(name = "cooperativa", nullable = false, length = 100)
	public String getCooperativa() {
		return this.cooperativa;
	}

	public void setCooperativa(String cooperativa) {
		this.cooperativa = cooperativa;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxi")
	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

}
