package com.aplicacionesa.modelo;

// Generated 14/01/2015 09:20:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name = "carrera", catalog = "aplicaciones")
public class Carrera implements java.io.Serializable {

	private Integer idCarrera;
	private Tarifa tarifa;
	private Usuario usuario;
	private String origen;
	private String destino;
	private String tiempo;
	private double kmRecorridos;
	private double precio;
	private Date fecha;
	private double latitudOrigen;
	private double longitudOrigen;
	private double latitudDestino;
	private double longitudDestino;
	private String estado;

	public Carrera() {
	}

	public Carrera(Tarifa tarifa, Usuario usuario, String origen,
			String destino, String tiempo, double kmRecorridos, double precio,
			Date fecha, double latitudOrigen, double longitudOrigen,
			double latitudDestino, double longitudDestino, String estado) {
		this.tarifa = tarifa;
		this.usuario = usuario;
		this.origen = origen;
		this.destino = destino;
		this.tiempo = tiempo;
		this.kmRecorridos = kmRecorridos;
		this.precio = precio;
		this.fecha = fecha;
		this.latitudOrigen = latitudOrigen;
		this.longitudOrigen = longitudOrigen;
		this.latitudDestino = latitudDestino;
		this.longitudDestino = longitudDestino;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_carrera", unique = true, nullable = false)
	public Integer getIdCarrera() {
		return this.idCarrera;
	}

	public void setIdCarrera(Integer idCarrera) {
		this.idCarrera = idCarrera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarifa", nullable = false)
	public Tarifa getTarifa() {
		return this.tarifa;
	}

	public void setTarifa(Tarifa tarifa) {
		this.tarifa = tarifa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "origen", nullable = false, length = 50)
	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	@Column(name = "destino", nullable = false, length = 50)
	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	@Column(name = "tiempo", nullable = false, length = 45)
	public String getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "km_recorridos", nullable = false, precision = 22, scale = 0)
	public double getKmRecorridos() {
		return this.kmRecorridos;
	}

	public void setKmRecorridos(double kmRecorridos) {
		this.kmRecorridos = kmRecorridos;
	}

	@Column(name = "precio", nullable = false, precision = 22, scale = 0)
	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 0)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "latitud_origen", nullable = false, precision = 22, scale = 0)
	public double getLatitudOrigen() {
		return this.latitudOrigen;
	}

	public void setLatitudOrigen(double latitudOrigen) {
		this.latitudOrigen = latitudOrigen;
	}

	@Column(name = "longitud_origen", nullable = false, precision = 22, scale = 0)
	public double getLongitudOrigen() {
		return this.longitudOrigen;
	}

	public void setLongitudOrigen(double longitudOrigen) {
		this.longitudOrigen = longitudOrigen;
	}

	@Column(name = "latitud_destino", nullable = false, precision = 22, scale = 0)
	public double getLatitudDestino() {
		return this.latitudDestino;
	}

	public void setLatitudDestino(double latitudDestino) {
		this.latitudDestino = latitudDestino;
	}

	@Column(name = "longitud_destino", nullable = false, precision = 22, scale = 0)
	public double getLongitudDestino() {
		return this.longitudDestino;
	}

	public void setLongitudDestino(double longitudDestino) {
		this.longitudDestino = longitudDestino;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
